version: '3.8'
services:
  db:
    image: postgres:14
    container_name: referenced-payments-db
    restart: always
    environment:
      POSTGRES_USER: pagos_user
      POSTGRES_PASSWORD: pagos_pass
      POSTGRES_DB: referenced_payments
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - referenced-network

  apiback:
    build: .
    container_name: referenced-payments-api
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/referenced_payments
      SPRING_DATASOURCE_USERNAME: pagos_user
      SPRING_DATASOURCE_PASSWORD: pagos_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - referenced-network

volumes:
  pgdata:

networks:
  referenced-network:
    driver: bridge
